language: rust
script:
  - cargo build --release --verbose --all
  - cargo test --verbose --all

deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file: "tailf"
  skip_cleanup: true
  on:
    tags: true