dist: tailf
language: rust
services: docker
sudo: required

script:
  - cargo build --release --verbose --all
  - cargo test --verbose --all

env:
  global:
    # TODO Update this to match the name of your project.
    - CRATE_NAME=tailf
  
deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file: $CRATE_NAME
  file_glob: true
  skip_cleanup: true
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo