[package]
name = "tailf"
version = "0.1.0"
authors = ["Weihua Liu <auhiewuil@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.4.2"
